#!/bin/bash --login
#SBATCH -J test1_leakyrelu
#SBATCH -N 1
#SBATCH --cpus-per-task=1
#SBATCH --mem=12G
#SBATCH --gres=gpu:v100:1
#SBATCH --time=00:10:00



########## Command Lines to Run ##########
 
#module load powertools/1.2 

nvcc 1D.cu

./a.out 32000 1
./a.out 32000 2
./a.out 32000 4
./a.out 32000 8
./a.out 32000 32
./a.out 32000 64


./a.out 64000 1
./a.out 64000 2
./a.out 64000 4
./a.out 64000 8
./a.out 64000 32
./a.out 64000 64



 
scontrol show job $SLURM_JOB_ID     ### write job information to SLURM output file.
js -j $SLURM_JOB_ID                 ### write resource usage to SLURM output file (powertools command).
